# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.27.9/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.27.9/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/valentinamoruzzi/Documents/GitHub/SIRproject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/valentinamoruzzi/Documents/GitHub/SIRproject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.27.9/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.27.9/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/valentinamoruzzi/Documents/GitHub/SIRproject/CMakeFiles /Users/valentinamoruzzi/Documents/GitHub/SIRproject//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/valentinamoruzzi/Documents/GitHub/SIRproject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sir

# Build rule for target.
sir: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sir
.PHONY : sir

# fast build rule for target.
sir/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sir.dir/build.make CMakeFiles/sir.dir/build
.PHONY : sir/fast

SIRproject.o: SIRproject.cpp.o
.PHONY : SIRproject.o

# target to build an object file
SIRproject.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sir.dir/build.make CMakeFiles/sir.dir/SIRproject.cpp.o
.PHONY : SIRproject.cpp.o

SIRproject.i: SIRproject.cpp.i
.PHONY : SIRproject.i

# target to preprocess a source file
SIRproject.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sir.dir/build.make CMakeFiles/sir.dir/SIRproject.cpp.i
.PHONY : SIRproject.cpp.i

SIRproject.s: SIRproject.cpp.s
.PHONY : SIRproject.s

# target to generate assembly for a file
SIRproject.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sir.dir/build.make CMakeFiles/sir.dir/SIRproject.cpp.s
.PHONY : SIRproject.cpp.s

src/sir_model.o: src/sir_model.cpp.o
.PHONY : src/sir_model.o

# target to build an object file
src/sir_model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sir.dir/build.make CMakeFiles/sir.dir/src/sir_model.cpp.o
.PHONY : src/sir_model.cpp.o

src/sir_model.i: src/sir_model.cpp.i
.PHONY : src/sir_model.i

# target to preprocess a source file
src/sir_model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sir.dir/build.make CMakeFiles/sir.dir/src/sir_model.cpp.i
.PHONY : src/sir_model.cpp.i

src/sir_model.s: src/sir_model.cpp.s
.PHONY : src/sir_model.s

# target to generate assembly for a file
src/sir_model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sir.dir/build.make CMakeFiles/sir.dir/src/sir_model.cpp.s
.PHONY : src/sir_model.cpp.s

src/sirdata.o: src/sirdata.cpp.o
.PHONY : src/sirdata.o

# target to build an object file
src/sirdata.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sir.dir/build.make CMakeFiles/sir.dir/src/sirdata.cpp.o
.PHONY : src/sirdata.cpp.o

src/sirdata.i: src/sirdata.cpp.i
.PHONY : src/sirdata.i

# target to preprocess a source file
src/sirdata.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sir.dir/build.make CMakeFiles/sir.dir/src/sirdata.cpp.i
.PHONY : src/sirdata.cpp.i

src/sirdata.s: src/sirdata.cpp.s
.PHONY : src/sirdata.s

# target to generate assembly for a file
src/sirdata.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sir.dir/build.make CMakeFiles/sir.dir/src/sirdata.cpp.s
.PHONY : src/sirdata.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sir"
	@echo "... SIRproject.o"
	@echo "... SIRproject.i"
	@echo "... SIRproject.s"
	@echo "... src/sir_model.o"
	@echo "... src/sir_model.i"
	@echo "... src/sir_model.s"
	@echo "... src/sirdata.o"
	@echo "... src/sirdata.i"
	@echo "... src/sirdata.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

